# general settings
name: Exp5-09_MoCHAformer4_stg1
model_type: MoCHAformer_Stg1_Model
num_gpu: auto  # set num_gpu: 0 for cpu mode
find_unused_parameters: True
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: MultiFrameVD
    type: MultiFrameVDPairedN2NRawDataset
    dataroot_gt: /code/datasets/RawVDemoire/train/gt_rgb
    dataroot_lq: /code/datasets/RawVDemoire/train/moire_raw
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: false
    use_rot: false
    crop_size: 256

    # data loader
    # This option is used in the build_dataloader function in basicsr/data/__init__.py
    use_shuffle: true
    batch_size_per_gpu: 3
    num_worker_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: MultiFrameVD
    type: MultiFrameVDPairedN2NRawDataset
    dataroot_gt: /code/datasets/RawVDemoire/test/gt_rgb
    dataroot_lq: /code/datasets/RawVDemoire/test/moire_raw
    io_backend:
      type: disk

    use_hflip: false
    use_rot: false

    batch_size: 2
    num_worker: 8

# network structures
network_g:
  type: MoCHAformer4
  stage: 1
  convnext_block_c: 3
  convnext_block_m: 3
  img_size: 128
  patch_size: 1
  in_chans: 4
  embed_dim: 96
  depths: [3,3,3]
  num_heads: [4,4,4]
  window_size: [2,7,7]
  mlp_ratio: 2
  qkv_bias: True
  qk_scale: False
  drop_rate: 0.
  attn_drop_rate: 0.
  drop_path_rate: 0.1
  ape: False
  patch_norm: True
  use_checkpoint: False
  upscale: 1
  img_range: 1.
  upsampler: 'pixelshuffle'
  downsample: True


path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.999]

  # original setting
  scheduler:
    type: MultiStepLR
    milestones: [250000]
    gamma: 0.5

  total_iter: 125000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv3_3': 0.5
    vgg_type: vgg16
    use_input_norm: true
    perceptual_weight: 0.1
    style_weight: 0
    range_norm: false
    criterion: l1


# validation settings
val:
  val_freq: !!float 25000
  save_img: true

  metrics:
    psnr:
      type: calculate_psnr_pt
      crop_border: 0
    ssim:
      type: calculate_ssim_pt
      crop_border: 0
    lpips:
      type: calculate_lpips_pt
      crop_border: 0

# logging settings
logger:
  print_freq: 500
  save_checkpoint_freq: !!float 10000
  use_tb_logger: true
  wandb:
    project: sRGBRAWVD
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
